# tools/expand_category_by_subtype.py — UNIQUE HOST
#
# Complement to tools/expand_category.py for the nodes of
# character/category_tree.py that do NOT have a wordnet_anchor (they are not
# a WordNet hyponym) but a `lexicon_subtype` instead -- the 15 `action`
# subtypes and 17 `quality` subtypes that the new lexicon carries (~8974
# words, see fullcompiler/README.md "Lexicon replaced entirely").
#
# Unlike expand_category.py (which looks up an anchor's hyponyms and
# crosses them against the lexicon's category), WordNet is not needed
# here: the subtype is ALREADY on every lexicon word (it was hand-
# classified in the chat that built the new lexicon), so all that is left
# is grouping.
#
# Runs AFTER tools/expand_category.py and M E R G E S its result (it does
# not overwrite it) -- both write to lexicon_db/db_category_words.py.
#
# Usage: python3 -m tools.expand_category_by_subtype

import ast

from questionnaire.category_tree import CATEGORY_TREE
from lexicon_db.db_lexicon import LEXICON


def walk_subtype_leaves(tree: dict = CATEGORY_TREE, path=()):
    """Yields (path, lexicon_subtype, lexicon_category) for every leaf
    marked with 'lexicon_subtype' (the new action/quality/
    object/place/body_part branches). lexicon_category is None unless the leaf
    needs it to disambiguate (e.g. "misc"/"building" could theoretically
    collide across categories)."""
    for key, node in tree.items():
        if not isinstance(node, dict):
            continue
        new_path = path + (key,)
        if "lexicon_subtype" in node:
            yield new_path, node["lexicon_subtype"], node.get("lexicon_category")
        elif "facets" in node:
            yield from walk_subtype_leaves(node["facets"], new_path)
        elif any(isinstance(v, dict) for v in node.values()):
            yield from walk_subtype_leaves(node, new_path)


def build_subtype_words():
    resolved = {}
    for path, subtype, category in walk_subtype_leaves():
        node_type = path[0] if path[0] in ("action", "quality") else None
        if node_type is None:
            # object/place/body_part live under biological/non_biological,
            # so there the real filter is lexicon_category, not path[0].
            words = sorted(
                w for w, d in LEXICON.items()
                if d.get("category") == category and d.get("subtype") == subtype
            )
        else:
            words = sorted(
                w for w, d in LEXICON.items()
                if d.get("node_type") == node_type and d.get("subtype") == subtype
            )
        resolved[path] = words
    return resolved


if __name__ == "__main__":
    new_words = build_subtype_words()
    total_new = sum(len(w) for w in new_words.values())

    # read what expand_category.py already wrote and merge (don't overwrite)
    with open("lexicon_db/db_category_words.py", encoding="utf-8") as f:
        src = f.read()
    start = src.index("CATEGORY_WORDS = {")
    existing = ast.literal_eval(src[start + len("CATEGORY_WORDS = "):].strip())

    merged = dict(existing)
    merged.update(new_words)

    with open("lexicon_db/db_category_words.py", "w", encoding="utf-8") as f:
        f.write('"""\n')
        f.write("db_category_words.py\n")
        f.write("Generated by tools/expand_category.py (nodes with a wordnet_anchor,\n")
        f.write("via WordNet hyponyms) + tools/expand_category_by_subtype.py\n")
        f.write("(nodes with a lexicon_subtype -- action/quality, grouped directly\n")
        f.write("by the `subtype` field each word already carries in\n")
        f.write("lexicon_db/db_lexicon.py, without going through WordNet).\n")
        f.write('"""\n\n')
        f.write("CATEGORY_WORDS = {\n")
        for path, words in merged.items():
            f.write(f"    {path!r}: {words!r},\n")
        f.write("}\n")

    print(f"New nodes (action/quality by subtype): {len(new_words)}")
    print(f"New words added: {total_new}")
    print(f"Total nodes in db_category_words.py now: {len(merged)}")
    print(f"Total words in db_category_words.py now: {sum(len(w) for w in merged.values())}")
