# tools/audit_homonyms.py — UNIQUE HOST
#
# Bounded sweep of HOMONYMS in db/db_lexicon.py (pending #1 of
# the session-state notes). It modifies nothing: it writes a report
# HOMONYMS_TO_REVIEW.md for review, to decide which to fix in
# db/db_lexicon_overrides.py.
#
# Usage (from the project root):   python tools/audit_homonyms.py
#
# WHAT IT DETECTS (only words with more than one sense; not the whole lexicon)
# ────────────────────────────────────────────────────────────────────
# A) SUBJECT vs OBJECT: the word ended up as biological but a good part of
#    its real frequency (SemCor, via lemma.count) is in NON-living
#    senses, or the other way around. It is the expensive error: "blade" ended up as a living plant
#    and was treated as a subject. noun.group senses are ignored: whether a
#    group ("crowd") is biological/non_biological is a design decision,
#    not homonymy.
# B) VERB/ADJECTIVE that is also a concrete noun: the word ended up
#    as action/quality (by the dominant POS in Brown, a 1961 corpus)
#    but its roleplay sense is a living noun or object ("raven",
#    "bear"). _is_confirmed_noun rejects node_type=action as a noun.
#
# LIMIT: SemCor frequency is GENERAL English, not roleplay. It is a
# filter so we don't review 9000 words by hand, not a verdict: each
# candidate is decided by a person.

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

from nltk.corpus import wordnet as wn
from db.db_lexicon import LEXICON
from db.db_lexicon_overrides import LEXICON_OVERRIDES

BIO_LEXNAMES = {"noun.animal", "noun.plant", "noun.person", "noun.body"}
# concrete noun senses that weigh more in roleplay than their general frequency
CONCRETE_NOUN_LEXNAMES = {"noun.animal", "noun.person", "noun.artifact", "noun.body", "noun.plant"}
MIN_NOUN_MASS_B = 2          # B: ignores words with very little evidence of use as a noun


def _mass(word, synsets):
    out = []
    for s in synsets:
        c = sum(l.count() for l in s.lemmas() if l.name().lower() == word.lower())
        out.append((s, c))
    return out


def audit():
    A, B = [], []
    for w, e in LEXICON.items():
        if w in LEXICON_OVERRIDES:
            continue  # already corrected by hand
        nt = e.get("node_type")

        if nt in ("biological", "non_biological"):
            senses = [(s, c) for s, c in _mass(w, wn.synsets(w, pos=wn.NOUN))
                      if s.lexname() != "noun.group"]
            if len(senses) < 2:
                continue
            cur_bio = nt == "biological"
            cur = sum(c for s, c in senses if (s.lexname() in BIO_LEXNAMES) == cur_bio)
            opp = sum(c for s, c in senses if (s.lexname() in BIO_LEXNAMES) != cur_bio)
            if opp > 0 and opp / (cur + opp) >= 0.3:
                top_opp = max((x for x in senses if (x[0].lexname() in BIO_LEXNAMES) != cur_bio),
                              key=lambda x: x[1])[0]
                A.append((w, e["category"], nt, cur, opp, top_opp.lexname(), top_opp.definition()))

        elif nt in ("action", "quality"):
            noun_senses = [(s, c) for s, c in _mass(w, wn.synsets(w, pos=wn.NOUN))
                           if s.lexname() in CONCRETE_NOUN_LEXNAMES]
            noun_mass = sum(c for s, c in noun_senses)
            if noun_mass < MIN_NOUN_MASS_B:
                continue
            other_pos = wn.VERB if nt == "action" else wn.ADJ
            other_mass = sum(c for s, c in _mass(w, wn.synsets(w, pos=other_pos)))
            if noun_mass >= other_mass:
                top = max(noun_senses, key=lambda x: x[1])[0]
                B.append((w, e["category"], nt, other_mass, noun_mass, top.lexname(), top.definition()))

    A.sort(key=lambda r: -(r[3] + r[4]))
    B.sort(key=lambda r: -r[4])
    return A, B


def write_report(A, B, path):
    with open(path, "w", encoding="utf-8") as f:
        f.write("# Homonyms to review (generated by tools/audit_homonyms.py)\n\n")
        f.write("Each row is a CANDIDATE, not a verdict. To fix one, add it to\n")
        f.write("`db/db_lexicon_overrides.py::LEXICON_OVERRIDES`. Frequencies = SemCor (general English).\n\n")
        f.write(f"## A) Subject/object possibly inverted ({len(A)})\n\n")
        f.write("| word | today | current sense freq. | opposite sense freq. | most frequent opposite sense |\n|---|---|---|---|---|\n")
        for w, cat, nt, cur, opp, lex, d in A:
            f.write(f"| {w} | {cat}/{nt} | {cur} | {opp} | {lex}: {d[:70]} |\n")
        f.write(f"\n## B) Verb/adjective that is also a concrete noun ({len(B)})\n\n")
        f.write("| word | today | verb/adj freq. | noun freq. | most frequent noun |\n|---|---|---|---|---|\n")
        for w, cat, nt, other, noun, lex, d in B:
            f.write(f"| {w} | {cat}/{nt} | {other} | {noun} | {lex}: {d[:70]} |\n")


if __name__ == "__main__":
    A, B = audit()
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "HOMONYMS_TO_REVIEW.md")
    write_report(A, B, out)
    print(f"A) subject/object: {len(A)} candidates")
    print(f"B) verb/adj that is a concrete noun: {len(B)} candidates")
    print(f"Report: {os.path.normpath(out)}")
